name: Deploy Website

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      -uses: actions/checkout@v4
      -name: Check HTML file exists
        run: Is *.HTML

       -name: Check CSS file exists
         run: Is *.CSS

        -name: Check JS file exists
          run: Is *.JS
