name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 12
      -run: nmp ci
      -run: nmp test
      -run: nmp run build 
      -run: nmp run deploy
